-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.


CREATE TABLE IF NOT EXISTS public.team
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text COLLATE pg_catalog."default",
    CONSTRAINT team_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.team
    OWNER to postgres;

GRANT ALL ON TABLE public.team TO anon;

GRANT ALL ON TABLE public.team TO authenticated;

GRANT ALL ON TABLE public.team TO postgres;

GRANT ALL ON TABLE public.team TO service_role;


CREATE TABLE IF NOT EXISTS public.team_users
(
    team_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT team_users_pkey PRIMARY KEY (team_id, user_id),
    CONSTRAINT team_users_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.team (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT team_users_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.team_users
    OWNER to postgres;

GRANT ALL ON TABLE public.team_users TO anon;

GRANT ALL ON TABLE public.team_users TO authenticated;

GRANT ALL ON TABLE public.team_users TO postgres;

GRANT ALL ON TABLE public.team_users TO service_role;
