INSERT INTO public.integrations (id, name) VALUES ('b0d1d793-097b-44bb-9466-fa68f2f853b5', 'Testing Data');

INSERT INTO public.feedback(content, classification, source) VALUES ('I’m happy to share that I have started working as a Senior Full-Stack Developer at @_heroicstory ! 🚀 Huge thanks to @KennethCassel for referring and supporting me, you are awesome! And also @pointer_gg is a great place to learn web3! 💪 t.co/dgWsoVEbL6', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Just bought the dip & finished The Solid Solidity tutorial from @pointer_gg Beginner friendly & Beautifully crafted covering the basics. Highly recommend💯 Kudos to @KennethCassel & @callum_codes for this great initiative.👏 Looking forward to more guys🚀 #web3 Check it out 👇', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Effortlessly create Edge functions for your next @supabase based web/mobile project, and deploy on @deno_land ''s Edge platform. Supabase just rolled out one of the most sought-after feature⚡💪', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('My husband has never allowed me to write, as he doesn''t want me touching mens pens. However when I saw this product, I decided to buy it(using my pocket money) and so far it has been fabulous! Once I had learnt how to write, the feminine colour and the grip size(which was more suited to my delicate little hands) has enabled me to vent thoughts about new recipe ideas, sewing and gardening. My husband is less pleased with this product as he believes it will lead to more independence and he hates the feminine tingling sensation (along with the visions of fairies and rainbows) he gets whenever he picks it up.', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('just finished @pointer_gg solid solidity tutorial! super informative and helpful! i recommend to anyone that is interested in full-stack ''web3'' 🙂', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('.@Cron is on fire and they now shipped a feature I was missing forever in every calendar. Merged events!!!! - https://cron.com/changelog/2022-03-28-event-auto-merge', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('This is so good. My wife and I share calendars for kid logistics, so I’ve just gotten used to having double events all over my calendar. Thanks :)', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Thanks @BetterUptime for powering our Status page!', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Linear (@linear) is probably our fav tool for issue tracking. The integration with Github is really nice and it just makes our lives easier. Plus, Linear''s app design is just gorgeous. You can tell from the design that the team behind Linear is building it with love ❤️', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Thank you for the goodies.', 'positive', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');

INSERT INTO public.feedback(content, classification, source) VALUES ('Hi Ele, can you explain how can you possibly get away with MASSIVE standing charge price rise for NO REASON whatsoever?', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('@MyCompany, It is up there with one of the worst products that has ever been made these people could not organise a piss up in a brewery #BADproduct', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('I can''t believe that anyone would let @EnergyCompany exist, there service is aweful and they constantly ignore me. Their hold music is just as bad.', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('I have just seen online this morning that yourselves have capped the energy prices at maximum allowed by ofgem. Is this correct? Feel quite disheartened if it is like many on lower incomes we changed to bulb to reduce our utility bills.', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Why have my standing charges increased so much? Extortion?', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Look at this 💩💩💩💩💩💩 actually unbelievable how bad this merchandise is …. Absolute dog 💩 . Reminds me of the stores I seen in Florida with the knock off Disney t-shirts. But all this is on our team store embarrassing', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Biden is on the world stage at his press conference lying about America once again. It is a disgrace.', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('It is a disgrace', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('They think we are all Fools', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');
INSERT INTO public.feedback(content, classification, source) VALUES ('Here''s the thing. Pro sports franchises create all kinds of ugly jerseys, caps, etc., just to sell more merchandise and make more money.', 'negative', 'b0d1d793-097b-44bb-9466-fa68f2f853b5');